# Generated by Django 5.1.5 on 2025-04-03 20:05

from django.db import migrations
from django.utils import timezone

def populate_timestamps(apps, schema_editor):
    Product = apps.get_model('dashboard', 'Product')
    for product in Product.objects.all():
        product.created_at = timezone.now()
        product.updated_at = timezone.now()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_timestamps),
    ]
