# Generated by Django 5.1.5 on 2025-04-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_populate_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
