# Generated by Django 5.1.5 on 2025-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_borroweditem_is_returned_borroweditem_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
