# Generated by Django 5.1.5 on 2025-04-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_borrower_date_borrowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borroweditem',
            options={'ordering': ['-date_borrowed']},
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['-date_borrowed']},
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_items', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='dashboard.product'),
        ),
        migrations.AddIndex(
            model_name='borroweditem',
            index=models.Index(fields=['is_returned'], name='dashboard_b_is_retu_94e22a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['status'], name='dashboard_b_status_e5a27f_idx'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['due_date'], name='dashboard_b_due_dat_a02685_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='dashboard_p_name_91aa43_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='dashboard_p_categor_6141dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['-date'], name='dashboard_s_date_551ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['product'], name='dashboard_s_product_495522_idx'),
        ),
    ]
