# Generated by Django 5.1.5 on 2025-04-05 02:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sale_delete_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='recorded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='dashboard_p_stock_fa08d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='dashboard_p_price_3b5108_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='dashboard_p_is_acti_0dbf53_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-date'], name='dashboard_s_date_51d52d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product'], name='dashboard_s_product_80cf55_idx'),
        ),
    ]
