# Generated by Django 5.1.5 on 2025-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_sale_options_alter_sale_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
