# Generated by Django 5.1.5 on 2025-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_borrower_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='signature',
            field=models.ImageField(blank=True, help_text="Upload borrower's signature", null=True, upload_to='signatures/'),
        ),
    ]
