# Generated by Django 5.1.5 on 2025-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_name',
            field=models.CharField(error_messages={'unique': 'A borrower with this name already exists.'}, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='borrower',
            constraint=models.UniqueConstraint(fields=('borrower_name',), name='unique_borrower_name_case_insensitive'),
        ),
    ]
