# Generated by Django 5.1.5 on 2025-04-12 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_borrower_borrower_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for notifications', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Philippine mobile number (e.g., 09123456789 or +639123456789)', regex='^(\\+63|0)?(9\\d{9})$')]),
        ),
    ]
