# Generated by Django 5.1.5 on 2025-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_borrower_email_alter_borrower_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for notifications', max_length=100, null=True),
        ),
    ]
