# Generated by Django 5.2 on 2025-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_borrower_telegram_chat_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['borrower_name'], name='dashboard_b_borrowe_2f6359_idx'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['email'], name='dashboard_b_email_90b1f2_idx'),
        ),
    ]
