# Generated by Django 5.2 on 2025-04-13 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_borrower_dashboard_b_borrowe_2f6359_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borroweditem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='borroweditem',
            name='dashboard_b_is_retu_94e22a_idx',
        ),
        migrations.RemoveField(
            model_name='borroweditem',
            name='returned_date',
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='date_borrowed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
