# Generated by Django 4.2.21 on 2025-05-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_product_deleted_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_count', models.PositiveIntegerField()),
                ('physical_count', models.PositiveIntegerField()),
                ('discrepancy', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('adjusted', models.BooleanField(default=False)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='dashboard.product')),
            ],
            options={
                'ordering': ['-audit_date'],
                'indexes': [models.Index(fields=['audit_date'], name='dashboard_i_audit_d_c6fa5f_idx'), models.Index(fields=['adjusted'], name='dashboard_i_adjuste_0ddf10_idx')],
            },
        ),
    ]
