# Generated by Django 4.2.21 on 2025-05-17 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_alter_borrower_email_alter_borrower_signature'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrower',
            name='unique_borrower_name_case_insensitive',
        ),
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='borrower_name',
            field=models.CharField(error_messages={'unique': 'A borrower with this name already exists.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['user'], name='dashboard_b_user_id_9bc0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user'], name='dashboard_p_user_id_c6cd57_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrower',
            constraint=models.UniqueConstraint(fields=('user', 'borrower_name'), name='unique_borrower_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_product_name_per_user'),
        ),
    ]
