# Generated by Django 4.2.21 on 2025-05-17 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0022_remove_borrower_unique_borrower_name_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['user'], name='dashboard_i_user_id_ee842b_idx'),
        ),
    ]
