# Generated by Django 4.2.21 on 2025-05-17 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_products_to_superuser(apps, schema_editor):
    Product = apps.get_model('dashboard', 'Product')
    User = apps.get_model('auth', 'User')
    
    # Get the first superuser
    superuser = User.objects.filter(is_superuser=True).first()
    
    if superuser:
        # Assign all products without a user to the superuser
        Product.objects.filter(user__isnull=True).update(user=superuser)

def reverse_func(apps, schema_editor):
    # No need to reverse this operation
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_inventoryaudit_user_and_more'),
    ]

    operations = [
        # First assign products to superuser
        migrations.RunPython(assign_products_to_superuser, reverse_func),
        
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auth.user'),
        ),
    ]
