# Generated by Django 4.2.21 on 2025-05-17 05:39

from django.db import migrations

def assign_products_to_superuser(apps, schema_editor):
    Product = apps.get_model('dashboard', 'Product')
    User = apps.get_model('auth', 'User')
    
    # Get the first superuser
    superuser = User.objects.filter(is_superuser=True).first()
    
    if superuser:
        # Assign all products without a user to the superuser
        Product.objects.filter(user__isnull=True).update(user=superuser)

def reverse_func(apps, schema_editor):
    # No need to reverse this operation
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_product_user'),
    ]

    operations = [
        migrations.RunPython(assign_products_to_superuser, reverse_func),
    ]
