# Generated by Django 4.2.21 on 2025-05-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_sales_to_product_owners(apps, schema_editor):
    Sale = apps.get_model('dashboard', 'Sale')
    
    # Update all sales to be owned by the product owner
    for sale in Sale.objects.filter(user__isnull=True).select_related('product__user'):
        sale.user = sale.product.user
        sale.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20250517_1339'),
    ]

    operations = [
        # First assign sales to product owners
        migrations.RunPython(assign_sales_to_product_owners, reverse_func),
        
        # Then make the field non-nullable and add indexes
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='auth.user'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='dashboard_s_date_b76b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user'], name='dashboard_s_user_id_db4d70_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product'], name='dashboard_s_product_80cf55_idx'),
        ),
    ]
