# Generated by Django 4.2.21 on 2025-05-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_update_borrower_user'),
        ('dashboard', '0027_assign_sales_to_product_owners'),
    ]

    operations = [
    ]
